FROM amazoncorretto:21
LABEL maintainer="itsupport@gmail.com"
ADD target/project-heatmap-ui-0.0.1-SNAPSHOT.jar project-heatmap-ui-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","project-heatmap-ui-0.0.1-SNAPSHOT.jar"]
EXPOSE 8102