FROM amazoncorretto:21
LABEL maintainer="itsupport@gmail.com"
ADD target/project-stock-data-0.0.1-SNAPSHOT.jar project-stock-data-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","project-stock-data-0.0.1-SNAPSHOT.jar"]
EXPOSE 8101