FROM amazoncorretto:21
LABEL maintainer="itsupport@gmail.com"
ADD target/project-data-provider-0.0.1-SNAPSHOT.jar project-data-provider-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","project-data-provider-0.0.1-SNAPSHOT.jar"]
EXPOSE 8100